name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['hulo', 'opencmd']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 检查是否有更新
      - name: Check for updates
        id: check-updates
        run: |
          if ! git diff HEAD^ HEAD --quiet ${{ matrix.directory }}; then
            echo "Changes found in directory '${{ matrix.directory }}'"
            echo "::set-output name=updated::true"
          fi

      # 创建压缩文件
      - name: Create ZIP file
        if: steps.check-updates.outputs.updated == 'true'
        run: |
          cd ${{ matrix.directory }}
          zip -r ../${{ matrix.directory }}.zip .
          echo "Created ${{ matrix.directory }}.zip"

      # 发布新版本
      - name: Publish release
        if: always()
        needs: [create-zip-hulo, create-zip-opencmd]
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release latest
          draft: false
          files: |
            ${{ contains(matrix.directory, 'hulo') ? 'hulo.zip' : '' }}
            ${{ contains(matrix.directory, 'opencmd') ? 'opencmd.zip' : '' }}
