name: Publish Release

on:
  push:
    branches:
      - main
env:
  COMMIT_MSG: ${{ github.sha }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x
#       - name: Install dependencies
#         run: pip install -r requirements.txt
#       - name: Publish Release
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           GH_EMAIL: ${{ secrets.EMAIL }}
#           GH_SHA: ${{ github.sha }}
#         run: python main.py
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic .\aa\
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
