name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python main.py
      - name: Upload to this repo
        run: |
          git config --global user.name "ansurfen"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m '${{ env.COMMIT_MSG }}'
          git push origin
        env:
          COMMIT_MSG: ${{ github.sha }}
